import { Project, Skill, Experience, Service } from './types';

export const SKILLS: Skill[] = [
  { name: 'React', icon: 'Atom', level: 95, category: 'Frontend' },
  { name: 'TypeScript', icon: 'Code2', level: 90, category: 'Frontend' },
  { name: 'HTML', icon: 'FileJson', level: 98, category: 'Frontend' },
  { name: 'CSS', icon: 'Palette', level: 95, category: 'Frontend' },
  { name: 'Tailwind CSS', icon: 'Wind', level: 98, category: 'Frontend' },
  { name: 'Bootstrap', icon: 'Layout', level: 85, category: 'Frontend' },
  { name: 'React Query', icon: 'Database', level: 88, category: 'Frontend' },
  { name: 'API Integration', icon: 'Link', level: 92, category: 'Frontend' },
  { name: 'Git', icon: 'GitBranch', level: 92, category: 'Tools' },
  { name: 'GitHub', icon: 'Github', level: 95, category: 'Tools' },
  { name: 'CI/CD', icon: 'Repeat', level: 85, category: 'DevOps' },
  { name: 'Vercel', icon: 'Cloud', level: 90, category: 'Hosting' },
  { name: 'Netlify', icon: 'CloudRain', level: 90, category: 'Hosting' },
  { name: 'Render', icon: 'Server', level: 88, category: 'Hosting' },
  { name: 'Cross-Browser Compatibility', icon: 'Globe', level: 88, category: 'Best Practices' },
  { name: 'Bun', icon: 'Package', level: 75, category: 'Tools' },
  { name: 'PostHog', icon: 'TrendingUp', level: 80, category: 'Analytics' },
];

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'E-Commerce Platform',
    description: 'A full-featured online store with cart functionality, secure checkout, and product management.',
    image: 'https://res.cloudinary.com/dfcr3ut7b/image/upload/v1767283080/Screenshot_2026-01-01_165729_vm3vmj.png',
    techStack: ['React', 'Tailwind CSS', 'Redux'],
    liveUrl: 'https://yamlfoods.ng/',
    githubUrl: 'ttps://github.com/yamltech/grocery-shop',
    category: 'Fullstack',
  },
  {
    id: '2',
    title: 'Yamltech',
    description: 'Yamltech is a portfolio IT solutions website focused on delivering reliable, secure, and responsive technology services for businesses.',
    image: 'https://res.cloudinary.com/dfcr3ut7b/image/upload/v1767328654/yamltechl%20landingpage.png',
    techStack: ['React', 'TypeScript', 'React Query'],
    liveUrl: 'https://yamltech.com/',
    githubUrl: '#',
    category: 'API-based',
  },
  {
    id: '3',
    title: 'Country Info Dashboard',
    description: 'Interactive website that shows country information and other information API with multi-city support and dynamic backgrounds.',
    image: 'https://res.cloudinary.com/dfcr3ut7b/image/upload/v1767799281/Screenshot_2026-01-07_161751_cd1skd.png',
    techStack: ['React', 'API Integration', 'Motion'],
    liveUrl: 'https://rest-county-api.netlify.app/',
    githubUrl: 'https://github.com/chikamso-cmd/Rest-Api-County',
    category: 'API-based',
  },
  {
    id: '4',
    title: 'Portfolio Design System',
    description: 'A comprehensive UI library built with accessibility and performance at its core.',
    image: 'https://res.cloudinary.com/dfcr3ut7b/image/upload/v1767290067/Screenshot_2026-01-01_185351_rpk2rz.png',
    techStack: ['React', 'TypeScript', 'Tailwind'],
    liveUrl: 'https://elaborate-souffle-35aec0.netlify.app/',
    githubUrl: 'https://github.com/chikamso-cmd/Portfolio12',
    category: 'Fullstack',
  },
  {
    id: '5',
    title: 'Bump2Baby',
    description: 'Bump2Baby is a comprehensive maternal health platform designed to guide expectant mothers through their pregnancy journey with personalized tracking, expert health insights, and essential care resources',
    image: 'https://res.cloudinary.com/dfcr3ut7b/image/upload/v1768566261/Screenshot_2026-01-15_174324_wtukup.png',
    techStack: ['React', 'TypeScript', 'Tailwind'],
    liveUrl: 'https://github.com/chikamso-cmd/Bump2Baby',
    githubUrl: 'https://bump-2-baby.netlify.app/',
    category: 'React',
  },
  {
    id: '6',
    title: 'AxiomVault llc',
    description: 'Advanced artificial intelligence continuously monitors employee records and bank accounts to identify suspicious activities, duplicate accounts, and financial irregularities. This proactive approach helps prevent fraud, ensures compliance, and maintains the integrity of the organization’s operations.',
    image: '/axiom.JPG',
    techStack: ['React', 'TypeScript', 'Tailwind'],
    liveUrl: 'https://axiomvault.netlify.app',
    githubUrl: 'https://github.com/AxiomVault01/Axiom-Vault',
    category: 'Fullstack',
  },
  {
    id: '7',
    title: 'OgaLandLord',
    description: 'OgaLandlord is a revolutionized rental market by developing an innovative platform that directly connects tenants with vetted agents, eradicating unfair overpricing and ensuring a seamless rental experience. By leveraging technology, OgaLandlord empowers tenants to find affordable housing while providing agents with a reliable channel to connect with potential renters.',
    image: '/land.JPG',
    techStack: ['React', 'TypeScript', 'Tailwind', "ReactQuery"],
    liveUrl: 'https://ogalandlord.netlify.app',
    githubUrl: 'https://github.com/ogaLandLords/frontend',
    category: 'Fullstack',
  },
];

export const EXPERIENCE: Experience[] = [
  {
    id: '1',
    company: 'Yamltech inc.',
    role: 'Frontend Developer',
    period: '2023 - 2024',
    description: 'Built and maintained responsive, accessible user interfaces using React and TypeScript; collaborated with backend engineers to integrate APIs and improve performance and developer workflows.',
  },
  {
    id: '2',
    company: 'Creative Web Studio',
    role: 'Frontend Developer',
    period: '2020 - 2022',
    description: 'Delivered client-facing web projects from design to production, translating visual designs into interactive, cross-browser-compatible websites while ensuring performance and SEO best practices.',
  },
  {
    id: '3',
    company: 'AXIOMVAULT LLC',
    role: 'Frontend Developer',
    period: '2026 - till present',
    description: 'Leading frontend development for secure enterprise applications; responsible for performance optimization, component architecture, and implementing CI/CD and observability integrations.',
  },
  {
    id: '4',
    company: 'OgaLandLord',
    role: 'Frontend Developer',
    period: '2026 - till present',
    description: 'Built the scalable marketplace frontend focused on real-world usability, responsive design, and fast load times; worked closely with product and backend teams to ship iterative improvements.',
  },
  
  {
    id: '5',
    company: 'MpfStudio91',
    role: 'Lead Frontend Developer',
    period: '2026 - till present',
    description: 'Architected component libraries and frontend best practices, mentored engineers, and established testing and accessibility standards to improve delivery quality across projects.',
  },
];

export const SERVICES: Service[] = [
  {
    id: '1',
    title: 'Build Responsive Web Apps',
    description: 'Mobile-first, high-performance web applications that work seamlessly across all devices.',
    iconName: 'Smartphone',
  },
  {
    id: '2',
    title: 'Integrate APIs',
    description: 'Connecting your frontend with powerful backends and third-party services securely.',
    iconName: 'Zap',
  },
  {
    id: '3',
    title: 'Optimize Performance',
    description: 'Ensuring your website loads instantly and provides a smooth user experience.',
    iconName: 'Gauge',
  },
  {
    id: '4',
    title: 'Create Reusable UI Components',
    description: 'Developing modular, accessible, and well-documented component libraries.',
    iconName: 'Component',
  },
];
